name: CI/CD Pipeline Package TEST

on:
  workflow_dispatch:
    inputs:
      processor:
        description: 'Choose the processor type (gpu, cpu, zluda)'
        required: false
        default: 'gpu'

env:
  FORCE_COLOR: "1"
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PORT: ${{ secrets.SSH_PORT || 22 }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  PROCESSOR: ${{ github.event.inputs.processor || 'gpu' }}  # Default to 'gpu' if not provided

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        target: [windows]
        include:
          - target: "windows"
            output-format: "msi"
            pre-command: |
              choco install visualstudio2022buildtools --confirm
              choco install visualstudio2022-workload-vctools --confirm
              choco install wixtoolset --version 4.0.5 --confirm
            runs-on: "windows-latest"
            python-version: "3.10"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test file
        shell: pwsh  # PowerShell для Windows
        run: |
          New-Item -ItemType Directory -Force -Path portable/dist
          Set-Location -Path portable/dist
          Invoke-WebRequest -Uri "https://wunjo.online/media/dist/v2-0-7/wunjo_2-0-7b1pro_win.msi" -OutFile "wunjo_2-0-7b1pro_win.msi"

      - name: Setup SSH
        if: env.SSH_PRIVATE_KEY != ''
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        if: env.SSH_PRIVATE_KEY != '' && env.SSH_PORT != '' && env.SSH_USER != '' && env.SSH_HOST != ''
        working-directory: portable
        run: |
          scp -r -P ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no -r dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/